Timer
Gouravchawla/pomodoro pull request #3
Opened 2018-01-27 15:46 UTC by Gouravchawla

Adds timer functionality with start, stop, resume and pause.

2018-01-27 16:29 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let minutes = 25;
we should add this to service.

2018-01-27 16:29 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let seconds = 0;
we should add this to service.

2018-01-27 16:30 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let setDisplayTimer = function(minutes, seconds) {
Comment missing on function

2018-01-27 16:30 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let clock = function() {
Comment missing on function

2018-01-27 16:31 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +      minutes = 10;
why minutes = 10 ?

2018-01-27 16:34 UTC, Nikhilkapoor20 requested changes
check comments

2018-01-27 16:36 UTC, Gouravchawla commented on app/modules/timer/controllers/timer.controller.js
> +      minutes = 10;
This is supposed to be 25.

2018-02-02 13:31 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let minutes = 25;
on stop it is not resetting to 00 : 00

2018-02-03 08:43 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +        if(seconds === 0) {
space after if and function is missing

2018-02-03 08:43 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +      if(minutes === 0) {
space after if and function is missing

2018-02-03 08:44 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +    let resetTimer = function() {
space after if and function is missing

2018-02-03 08:45 UTC, Nikhilkapoor20 commented on app/modules/timer/controllers/timer.controller.js
> +      minutes = 10;
reset function should set time back to 25:00 s , please consider this case too

2018-02-19 04:13 UTC, dotgourav reviewed
Merging this as I’m changing the code structure inthe controller.

2018-02-24 06:44 UTC, merged